---
user: www-data
group: www-data
environment: production
address: 0.0.0.0
port: 3000
servers: 2
threaded: true
no-epoll: true
daemonize: true
socket: tmp/sockets/cwo.sock
wait: 30
timeout: 30
max_conns: 1024
max_persistent_conns: 100
threadpool_size: 20
chdir: "/var/www/clickworkorange"
log: "/var/www/clickworkorange/log/thin.log"
pid: tmp/pids/thin.pid
tag: clickworkorange
require: []
